services:
  - type: web
    name: rasa-bot
    env: docker
    plan: free
    autoDeploy: true
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /status
    envVars:
      - key: PORT
        value: 5005
